@startuml

partition CAADE  #cccccc {
  (*) --> "Create Project"
  --> "Write Code"
}

partition "CICD" #lightgreen {
  "Write Code" --> "Define Pipeline"
  "Define Pipeline" --> "Define Agents"
  "Define Agents" --> "Build Code"
  "Build Code" --> "Test Code"
  "Test Code" --> "Deploy Code"
  "Deploy Code" --> (*)
}

@enduml
