@startuml
Actor "actorName" as A

box "Manage-Application" #lightblue
participant CLI as CLI
participant Web as Web
participant "caade" as S
A -> CLI : caade-application-publish()
CLI -> S : application/publish()
A -> Web : application/publish()
Web -> S : application/publish()
end box

@enduml
