@startuml

partition "swarm-node-agent" {

}

partition User  #cccccc {
  (*) --> "Create Project"
  --> "Write Code"
}

partition "swarm-node-agent" #lightblue {
  "Write Code" --> "Test Code"
  "Test Code" --> "Deploy Code"
  "Deploy Code" --> (*)
}

partition Used  #cccccc {
}
@enduml
