@startuml

node Build #lightgray {
    interface WebUI
    interface REST
    interface CLI
    component Portal #goldenrod
    component CICD #goldenrod {
        component master
    }
    component "Artifact\nRepository" as AR #plum
    component "Environment\nManager" as EM #plum
    component "Provision\nEngine" as PE #plum
    storage Storage <<Global>> #plum {
        database build_home #white
        database registry_home #white
        database portal_home #white
    }
}

rectangle Ports {
    9000 . WebUI
    5055 . REST
    50000 . CICD
    8000 . CICD
    5000 . Registry
}

Ports .. CAADE
cloud "External Cloud" {
    component GitHub
}

node Local #lightyellow {
    component build_agent as lba
}

cloud "Hybrid Cloud" as HC {
    node Dev #lightgreen {
        component build_agent as dba
    }
    node Test #pink {
        component build_agent as tba
    }
    node Production #lightblue {
        component build_agent as pba
    }
}
WebUI -- Portal
REST -- Portal
CLI -- Portal
Portal - portal_home
AR -- registry_home
master -- build_home
master -- lba
master -- dba
master -- tba
master -- pba
master <-- GitHub
Portal -- CICD
Portal -- AR
Local -> GitHub
@enduml
