@startuml
|Developer|
start
|#lightyellow|local|
        :create project;
        repeat
        :commit code;
|#lightgreen|dev|
        :integrate code;
        :build application;
        if(build status) then (failed)
            :debug application;
            detach
        endif
|#pink|test|
        :run unit tests;
        :run integration tests;
        if(test results?) then (failed)
            :debug application;
        endif
        repeat while(bugs found)
        :publish application;
|#lightblue|production|
        if(application deployed) then (not)
            :deploy application;
        else
            :update application;
        endif
        :start application;
        repeat
        :monitor application;
        if(SLA) then (not met)
            :scale application;
        endif
        repeat while(application alive)
@enduml
