@startuml

left to right direction

:Developer: as Dev
:DevOps: as DevOps
:Common Cloud Core: as C3
:SCM: as SCM
:CI/CD: as CICD

rectangle CAADE #lightblue {
    (Manage Application) as MA
    (Manage Code) as MC
    (Manage Build) as MB
    (Manage Environment) as ME
    (Manage Pipeline) as MP
    (Manage Project) as MProj
    (Manage Service) as MS
}

DevOps --> MB
DevOps --> ME
DevOps --> MP
DevOps --> MS
Dev --> MA
Dev --> MC
Dev --> MB
Dev --> MProj
Dev --> MS

MC --> SCM
ME --> C3
MB --> CICD
MP --> CICD
MA --> C3
MS --> C3

@enduml

