version: '3.1'

services:
  agent:
    image: madajaju/jenkins-swarm-node-agent
    deploy:
      mode: global
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    secrets:
      - source: jenkins-v1
        target: jenkins
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
        - /mnt/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
    command: --host unix:///var/run/docker.sock

secrets:
  jenkins-v1:
    file: ./jenkins-secret.txt

