version: '3.1'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    command: --host unix:///var/run/docker.sock
