@startuml
Actor "actorName" as A

box "Manage-Service" #lightblue
participant CLI as CLI
participant Web as Web
participant "caade" as S
A -> CLI : caade-service-publish()
CLI -> S : service/publish()
A -> Web : service/publish()
Web -> S : service/publish()
end box

@enduml
