@startuml

skinparam packageStyle rect
skinparam defaultFontSize 20

    package Portal #goldenrod { }
    package "CICD" #goldenrod { }
    package "Storage" #plum { }
    package "Artifact Repository" as AR #plum { }
    package "Environment Manager" as EM #plum { }
    package "Provision Engine" as PE  #plum { }
    cloud "Hybrid Cloud" as HC #ffffff {
        package "Local Environment" as LEnv #lightyellow { }
        package "Dev Environment" as DEnv #lightgreen { }
        package "Test Environment" as TEnv #pink { }
        package "Production Environment" as PEnv #lightblue { }
    }

Portal - CICD
Portal -- EM
CICD --> PE

EM ..> HC

PE --> LEnv
PE --> DEnv
PE --> TEnv
PE --> PEnv
Portal - AR
Portal - HC

CICD -> AR
LEnv --> AR
DEnv --> AR
TEnv --> AR
PEnv --> AR
AR -- Storage
CICD -- Storage

@enduml
